.PHONY: clean All

All:
	@echo "----------Building project:[ Michael - Debug ]----------"
	@cd "Michael" && "$(MAKE)" -f  "Michael.mk"
clean:
	@echo "----------Cleaning project:[ Michael - Debug ]----------"
	@cd "Michael" && "$(MAKE)" -f  "Michael.mk" clean
